#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi

if [ -d 'build' ] ; then
    rm -r build
fi

if [ -d 'site' ] ; then
    rm -r site
fi

if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi

if [ -d "src/pytest_unasync.egg-info" ] ; then
    rm -r src/pytest_unasync.egg-info
fi

if [ -d 'src' ] ; then
    find src -type f -name "*.py[co]" -delete
    find src -type d -name __pycache__ -delete
fi
