#!/bin/sh -e

export PREFIX=""
export PYTHON="python"

if [ -z $CI ]; then
  export PREFIX="venv/bin/"
  export PYTHON="../../${PREFIX}python"
fi

set -x

cd fixtures/pycomputer

../../scripts/clean

$PYTHON setup.py bdist_wheel
rm -rf pycomputer/_sync
mv build/lib/pycomputer/_sync pycomputer

../../scripts/clean
