#!/bin/sh -e

export PREFIX=""
if [ -d "venv" ]; then
  export PREFIX="venv/bin/"
fi

set -x


cd fixtures/pycomputer

../../scripts/clean

../../${PREFIX}python setup.py bdist_wheel
rm -rf pycomputer/_sync
mv build/lib/pycomputer/_sync pycomputer

../../scripts/clean
